version: '3'
services:
    asw-server:
        container_name: 'hackernews'
        build: .
        depends_on:
            - 'mariadb'
        ports:
            - '13001:13001'
    mariadb:
        container_name: 'mariadb'
        image: 'mariadb:10'
        environment:
            - 'MARIADB_PASSWORD=p4ssw0rd'
            - 'MARIADB_USER=user'
            - 'MARIADB_DATABASE=hackernews'
            - 'MARIADB_RANDOM_ROOT_PASSWORD=yes'
        volumes:
            - './mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql'
            - './mariadb/dbdata:/var/lib/mysql'
